/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlqcafe;

import javax.swing.JOptionPane;


public class GiaoDienNhanVien extends javax.swing.JFrame {
    private final NguoiDung staff;
        
    public GiaoDienNhanVien(NguoiDung user) {
        initComponents();
        this.staff = user;
        setResizable(false);
        setLocationRelativeTo(this);        
    }     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_nuocUong = new javax.swing.JButton();
        jButton_banCafe = new javax.swing.JButton();
        jButton_datBan = new javax.swing.JButton();
        jLabel_ten = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_thongTin = new javax.swing.JButton();
        jButton_dangXuat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_nuocUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/coffee (1)_(1).png"))); // NOI18N
        jButton_nuocUong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_nuocUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuocUongActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_nuocUong, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 80, 50));

        jButton_banCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/cafe.png"))); // NOI18N
        jButton_banCafe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_banCafe.setMaximumSize(new java.awt.Dimension(65, 41));
        jButton_banCafe.setMinimumSize(new java.awt.Dimension(65, 41));
        jButton_banCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_banCafeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_banCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 77, 55));

        jButton_datBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/coffee-table (1).png"))); // NOI18N
        jButton_datBan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_datBan.setMaximumSize(new java.awt.Dimension(65, 41));
        jButton_datBan.setMinimumSize(new java.awt.Dimension(65, 41));
        jButton_datBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_datBanActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_datBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 76, 75, 55));

        jLabel_ten.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_ten.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ten.setText("QUẢN LÝ QUÁN CAFE");
        jLabel_ten.setToolTipText("");
        getContentPane().add(jLabel_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 392, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đồ uống");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 140, 80, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bán hàng");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 77, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Đặt bàn");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 150, 75, 35));

        jButton_thongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/info.png"))); // NOI18N
        jButton_thongTin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_thongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thongTinActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_thongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 98, 66));

        jButton_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/logout.png"))); // NOI18N
        jButton_dangXuat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dangXuatActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_dangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 98, 66));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Thông tin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 97, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Đăng xuất");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 97, 25));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Hinhnen-Coffee-3.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jButton_nuocUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuocUongActionPerformed
        DoUong doUong = new DoUong(this.staff);
        this.setVisible(false);
        doUong.setVisible(true);
    }//GEN-LAST:event_jButton_nuocUongActionPerformed

    private void jButton_banCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_banCafeActionPerformed
        // TODO add your handling code here:
        BanHang banHang = new BanHang(this.staff, "");
        this.setVisible(false);
        banHang.setVisible(true);    
    }//GEN-LAST:event_jButton_banCafeActionPerformed

    private void jButton_datBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_datBanActionPerformed
        DatBan db = new DatBan(this.staff);
        this.setVisible(false);
        db.setVisible(true);
    }//GEN-LAST:event_jButton_datBanActionPerformed

    private void jButton_thongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thongTinActionPerformed
        ThongTin tt = new ThongTin(this.staff);
        this.setVisible(false);
        tt.setVisible(true);
    }//GEN-LAST:event_jButton_thongTinActionPerformed
            
    private void jButton_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dangXuatActionPerformed
        int Click = JOptionPane.showConfirmDialog(null, "Kết ca?", "Thông Báo", 2);
        if(Click == JOptionPane.YES_OPTION){            
            new XuLyChung().luuDN(staff.getManv(),"checkout");
            DangNhap dangnhap = new DangNhap();
            this.setVisible(false);
            dangnhap.setVisible(true);
        }
    }//GEN-LAST:event_jButton_dangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_banCafe;
    private javax.swing.JButton jButton_dangXuat;
    private javax.swing.JButton jButton_datBan;
    private javax.swing.JButton jButton_nuocUong;
    private javax.swing.JButton jButton_thongTin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_ten;
    // End of variables declaration//GEN-END:variables
}
