/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlqcafe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nhom 40
 */
public class LSThayDoi extends javax.swing.JFrame {
    private final NguoiDung staff;
    public static DefaultTableModel dtm;
    private boolean change = false; 
    
    public LSThayDoi(NguoiDung user) {
        initComponents();
        this.staff = user;
        jLabel_DIENTENNV.setText(staff.getHoten());
        setResizable(false);
        setLocationRelativeTo(this);
        layLSThayDoi();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ls = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel_DIENTENNV = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lịch sử thay đổi đồ uống");

        jTable_ls.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Ngày Cập Nhật", "Tên Sản Phẩm", "Loại Sản Phẩm", "DVT", "Số Lượng", "Đơn Giá (VND)", "Sale (%)", "Mã NV", "Chức Năng"
            }
        ));
        jTable_ls.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_ls);
        if (jTable_ls.getColumnModel().getColumnCount() > 0) {
            jTable_ls.getColumnModel().getColumn(0).setMinWidth(90);
            jTable_ls.getColumnModel().getColumn(0).setMaxWidth(150);
            jTable_ls.getColumnModel().getColumn(3).setMinWidth(130);
            jTable_ls.getColumnModel().getColumn(3).setMaxWidth(200);
            jTable_ls.getColumnModel().getColumn(4).setMinWidth(70);
            jTable_ls.getColumnModel().getColumn(4).setMaxWidth(150);
            jTable_ls.getColumnModel().getColumn(5).setMinWidth(50);
            jTable_ls.getColumnModel().getColumn(5).setMaxWidth(100);
            jTable_ls.getColumnModel().getColumn(6).setMinWidth(100);
            jTable_ls.getColumnModel().getColumn(6).setMaxWidth(150);
            jTable_ls.getColumnModel().getColumn(7).setMinWidth(70);
            jTable_ls.getColumnModel().getColumn(7).setMaxWidth(100);
            jTable_ls.getColumnModel().getColumn(8).setMinWidth(50);
            jTable_ls.getColumnModel().getColumn(8).setMaxWidth(100);
            jTable_ls.getColumnModel().getColumn(9).setMinWidth(100);
            jTable_ls.getColumnModel().getColumn(9).setMaxWidth(150);
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/smart-home.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_DIENTENNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_DIENTENNV.setText("DIỀN TÊN NV");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_DIENTENNV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_DIENTENNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GiaoDienChung gdc = new GiaoDienChung(this.staff);
        this.setVisible(false);
        gdc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void layLSThayDoi(){
        String sql= "SELECT LS.*, LSP.TENLSP, DT.TENDVT " +
                    "FROM LSTHAYDOI AS LS, LOAISP AS LSP, DVT AS DT " +
                    "WHERE LS.MALSP = LSP.MALSP AND LS.MADVT = DT.MADVT";
        layDulieu(sql);
    }
    
    private void layDulieu(String sql){
        dtm = (DefaultTableModel)jTable_ls.getModel();
        dtm.setNumRows(0);        
        
        Vector vt ;
        try{
            Connection cn = ConnectDB.SQLConnect();
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                vt = new Vector();
                vt.add(rs.getString("MASP"));
                vt.add(rs.getString("NGAYCAPNHAT"));
                vt.add(rs.getString("TENSP"));
                vt.add(rs.getString("TENLSP"));
                vt.add(rs.getString("TENDVT"));
                vt.add(rs.getString("SOLUONG"));
                vt.add(rs.getString("DONGIA"));
                vt.add(rs.getString("GIAMGIA"));
                vt.add(rs.getString("MANV"));
                vt.add(rs.getString("CHUCNANG"));
                dtm.addRow(vt);
            }
            JOptionPane.showMessageDialog(this, "Đã cập nhật!");
            jTable_ls.setModel(dtm);
            rs.close();
            ps.close();
            cn.close();
        }catch(SQLException e){
            Logger.getLogger(DoUong.class.getName()).log(Level.SEVERE, null, e);
        }
    }
        
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_DIENTENNV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_ls;
    // End of variables declaration//GEN-END:variables
}
