/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlqcafe;

import javax.swing.JOptionPane;

/**
 *
 * @author hungh
 */
public class SLBanMax extends javax.swing.JFrame {
    private final NguoiDung staff;
    
    public SLBanMax(NguoiDung user) {        
        initComponents();
        this.staff = user;
        startFunctionalButtons();
        enableSoBanMax(false);     
        inSoBanMax();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_banMax = new javax.swing.JTextField();
        btn_Huy = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Luu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton_home = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Số lượng bàn tối đa:");

        btn_Huy.setText("Hủy");
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleHuy(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleSuaBanMax(evt);
            }
        });

        btn_Luu.setText("Lưu");
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleLuuBanMax(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("QUẢN LÝ SỐ LƯỢNG BÀN");

        jToggleButton_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/smart-home.png"))); // NOI18N
        jToggleButton_home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleGoToTrangChu(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_banMax, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton_home, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2))
                    .addComponent(jToggleButton_home, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_banMax, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void handleSuaBanMax(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleSuaBanMax
        // TODO add your handling code here:
        enableSoBanMax(true);
        btn_Sua.setEnabled(false);
        btn_Luu.setEnabled(true);
        btn_Huy.setEnabled(true);
        inSoBanMax();
    }//GEN-LAST:event_handleSuaBanMax

    private void handleLuuBanMax(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleLuuBanMax
        // TODO add your handling code here:
        String banMax = txt_banMax.getText().trim();
        if(!banMax.equals("")){
            if(banMax.matches("[0-9]+")){
                int soBan = Integer.parseInt(banMax);
                if(soBan > 0){
                    int click = JOptionPane.showConfirmDialog(this , "Nếu xác nhận thay đổi số lượng bàn, TẤT CẢ BÀN sẽ được reset \nvề Trạng thái KHÔNG CÓ KHÁCH ngay bây giờ."
                            + "\n\nĐể an toàn, hãy thay đối vào thời điểm trước giờ bắt đầu làm việc của ngày hôm sau."
                            + "\n\nXác nhận thay đổi?", "Xác nhận", 2);
                    if(click == JOptionPane.YES_OPTION){
                        //thao tac len table TACVU
                        String sql = "UPDATE TACVU SET SLBANMAX = " + banMax + " WHERE ID = 1";
                        ConnectDB.queryUpdate(sql);
                        startFunctionalButtons();
                        inSoBanMax();
                        
                        //thao tac len table BAN
                        //xoa cac BAN CU trong table BAN
                        sql = "DELETE FROM BAN "
                                + " DBCC CHECKIDENT ('BAN', RESEED, 0)";
                        ConnectDB.queryUpdate(sql);                        
                        
                        //add lai cac BAN MOI      
                        int count = 1;
                        while(count <= soBan){
                            sql = "INSERT INTO BAN(TRANGTHAIRONG) VALUES (1)";
                            ConnectDB.queryUpdate(sql);
                            count++;
                        }
                    }
                }else JOptionPane.showMessageDialog(this, "Số lượng bàn tối đa không được nhỏ hơn hoặc bằng 0!");
            }else JOptionPane.showMessageDialog(this, "Số lượng bàn tối đa chỉ được nhập số!");
        }else JOptionPane.showMessageDialog(this, "Số lượng bàn tối đa không thể để trống!");        
    }//GEN-LAST:event_handleLuuBanMax

    private void handleHuy(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleHuy
        // TODO add your handling code here:
        enableSoBanMax(false);
        inSoBanMax();
        startFunctionalButtons();
    }//GEN-LAST:event_handleHuy

    private void handleGoToTrangChu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleGoToTrangChu
        GiaoDienChung gdc = new GiaoDienChung(this.staff);
        this.setVisible(false);
        gdc.setVisible(true);        
    }//GEN-LAST:event_handleGoToTrangChu
    
    public void startFunctionalButtons(){
        btn_Sua.setEnabled(true);
        btn_Luu.setEnabled(false);
        btn_Huy.setEnabled(false);
    }
    
    public void enableSoBanMax(boolean onOff){
        txt_banMax.setEnabled(onOff);
    }
    
    public static int getSoBanMax(){
        return Integer.parseInt(ConnectDB.selectSQLReturnOneValue("SLBANMAX", "TACVU", "ID = 1", "getSoBanMax", "SLBanMax"));
    }
    
    public void inSoBanMax(){
        txt_banMax.setText(String.valueOf(getSoBanMax()));
    }
        
    
    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SLBanMax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SLBanMax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SLBanMax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SLBanMax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SLBanMax().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Huy;
    private javax.swing.JButton btn_Luu;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton_home;
    private javax.swing.JTextField txt_banMax;
    // End of variables declaration//GEN-END:variables
}
