USE CAFESTORE
GO
CREATE PROC [dbo].[SP_INS_NHANVIEN] (
	@MANV NCHAR(10),
	@TENNV NVARCHAR(50),
	@NGAYSINH NVARCHAR(15),
	@GIOITINH NVARCHAR(6),
	@SDT NVARCHAR(15),
	@DIACHI NVARCHAR(50),
	@TAIKHOAN NVARCHAR(20),
	@MATKHAU NVARCHAR(20),
	@MACV INT
) AS
BEGIN
	INSERT INTO NHANVIEN(MANV,TENNV,NGAYSINH,GIOITINH,SDT,DIACHI,TAIKHOAN,MATKHAU,MACV)
	VALUES(@MANV,@TENNV,@NGAYSINH,@GIOITINH,@SDT,@DIACHI,@TAIKHOAN,@MATKHAU,@MACV)
END