USE CAFESTORE
GO
ALTER PROC [dbo].[SP_INS_PHIENLAMVIEC] (
	@MANV NCHAR(10),
	@CHECKIN VARCHAR(103),
	@CHECKOUT VARCHAR(103)
) AS
BEGIN
	INSERT INTO PHIENLAMVIEC(MANV,CHECKIN,CHECKOUT)
	VALUES(@MANV,CONVERT(DATETIME,@CHECKIN,103),CONVERT(DATETIME,@CHECKOUT,103))
END