USE QLCF
GO
ALTER PROC SP_INS_ENCRYPT_ADMIN
(		@TENDN NVARCHAR(10),
		@PASS VARCHAR(160),
		@NAME NVARCHAR(100)
) AS
BEGIN
	DECLARE @MK VARBINARY
	SET @PASS = HASHBYTES('MD5', @PASS )
	INSERT INTO Admin([USER],PASSWORD,NAME)
	VALUES (@TENDN,CONVERT(VARBINARY(256),@PASS),@NAME)
END

--EXEC SP_INS_ENCRYPT_ADMIN 'admin','admin','Admin'