USE QLcafe
GO
CREATE PROC SP_NHANVIEN_IDTUTANG
AS
BEGIN
	--KHOI TAO 2 BIEN MA TU SINH VA TONG SO HIEN CO
	DECLARE @AUTO_ID VARCHAR(10)
	DECLARE @MAX INT
	SELECT @MAX = COUNT(MANV) + 1 FROM NHANVIEN WHERE MANV LIKE 'NV'
	SET @AUTO_ID = 'NV' + RIGHT('0' + CAST(@MAX AS VARCHAR(8)),8)
	--KT MA TON TAI
	WHILE(EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV = @AUTO_ID))
	BEGIN
		SET @MAX = @MAX + 1
		SET @AUTO_ID = 'NV' + RIGHT('0' + CAST(@MAX AS VARCHAR(8)),8)
	END
	SELECT @AUTO_ID
END