USE QLcafe
GO
CREATE PROC SP_NHANVIEN_NEWID
AS
BEGIN
	DECLARE @AUTO_ID VARCHAR(10)
	SET @AUTO_ID = 'NV' + LEFT(NEWID(), 8)
	--CHI LAY 8 KY TU
	WHILE(EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV = @AUTO_ID))
	BEGIN
		SET @AUTO_ID = 'NV' + LEFT(NEWID(), 8)
	END
	SELECT @AUTO_ID
END