USE QLCF
GO
CREATE PROC SP_UPDATE_ENCRYPT_ADMIN
(		@TENDN NVARCHAR(10),
		@PASS VARCHAR(160),
		@NAME NVARCHAR(100)
) AS
BEGIN
	UPDATE Admin
	SET PASSWORD = CONVERT(VARBINARY(256),@PASS),
		NAME = @NAME
	WHERE Admin.[USER] = @TENDN
END